--- #YAML:1.0
name:               Pod-Advent
version:            0.08
abstract:           POD Formatter for The Perl Advent Calendar
author:
    - David Westbrook <dwestbrook@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Scalar:    0
    perl:          5.006001
    Perl::Tidy:    0
    Pod::Simple:   0
    Test::More:    0
    Text::Aspell:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
