--- #YAML:1.0
name:               Pod-Advent
version:            0.20
abstract:           POD Formatter for The Perl Advent Calendar
author:
    - David Westbrook <dwestbrook@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cwd:                  0
    ExtUtils::MakeMaker:  0
    File::Basename:       0
    IO::CaptureOutput:    0
    perl:                 5.006001
    Perl::Tidy:           20030726
    Pod::Simple:          3.06
    Test::Differences:    0
    Test::More:           0
    Text::Aspell:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
